### ISSUE TITLE
现在下载怎么都是源码包了

### ISSUE THREAD

**Issue by pengpan** [360EntSecGroup-Skylar/ElasticHD#24]
您好，刚找遍了您的项目wiki，在Releases下载的1.4也是源码包，不能直接解压、授权、运行；麻烦楼主看下  是我下载的有问题，还是现开放的下载包有问题；
或者直接给个下载地址；谢拉！

**Comment by wongchance** [comment]
https://github.com/360EntSecGroup-Skylar/ElasticHD/releases/download/1.4/elasticHD_windows_amd64.zip

**Comment by pengpan** [comment]
好，谢谢！
建议楼主修改下WIKI里的 Installation 链接成这个 [](https://github.com/360EntSecGroup-Skylar/ElasticHD/releases/)

**Comment by farmerx** [comment]
已修改
